"""
RagSentry Adapter — HTTP Wrapper
Generated by: skills/adapter-scaffolder

Use this template when your RAG system exposes an HTTP API but the response
shape requires custom extraction logic beyond simple dotted-path access.

For simpler cases, you can skip this file entirely and use the built-in
HTTP adapter directly:
    ragsentry run -e evalset.jsonl \
      -a "http://localhost:8000/api/query" \
      --adapter-type http \
      --answer-path "response.text" \
      --contexts-path "response.sources"
"""
from __future__ import annotations

import json
from typing import Any

import httpx

# --------------------------------------------------------------------------
# CONFIGURATION — replace these with your real values
# --------------------------------------------------------------------------
RAG_API_URL = "http://localhost:8000/api/query"  # Your RAG endpoint URL
REQUEST_TIMEOUT = 30  # Seconds


def query(question: str) -> dict[str, Any]:
    """
    RagSentry adapter: sends a question to an HTTP RAG endpoint and
    normalizes the response to the standard contract.

    Must return a dict with at minimum:
        { "answer": str, "contexts": list[str] }
    """
    # Build the request payload — adjust the key name to match your API
    payload = {"question": question}

    response = httpx.post(
        RAG_API_URL,
        json=payload,
        timeout=REQUEST_TIMEOUT,
    )
    response.raise_for_status()
    data = response.json()

    # --------------------------------------------------------------------------
    # EXTRACT — replace these with the real keys/paths from your API response
    # --------------------------------------------------------------------------
    # Example: if your API returns {"result": {"text": "...", "sources": [...]}}
    answer: str = data["answer"]

    # If contexts are objects, extract the text field:
    # contexts = [src["page_content"] for src in data["sources"]]
    contexts: list[str] = data["contexts"]

    return {
        "answer": answer,
        "contexts": contexts,
        "metadata": {k: v for k, v in data.items() if k not in ("answer", "contexts")},
    }
