"""
RagSentry Adapter — Shell Wrapper
Generated by: skills/adapter-scaffolder

Use this template when your RAG system is invoked as a subprocess/CLI tool.

For simpler cases where your CLI reads a question from stdin and prints JSON
to stdout, you can skip this file and use the built-in shell adapter:
    ragsentry run -e evalset.jsonl \
      -a "shell:python my_rag_cli.py" \
      --adapter-type shell
"""
from __future__ import annotations

import json
import subprocess
from typing import Any

# --------------------------------------------------------------------------
# CONFIGURATION — replace these with your real values
# --------------------------------------------------------------------------
RAG_COMMAND = ["python", "my_rag_cli.py"]  # Command to invoke your RAG tool
TIMEOUT_SECONDS = 60


def query(question: str) -> dict[str, Any]:
    """
    RagSentry adapter: invokes a RAG tool as a subprocess and parses
    the JSON output to match the standard contract.

    Must return a dict with at minimum:
        { "answer": str, "contexts": list[str] }
    """
    result = subprocess.run(
        RAG_COMMAND,
        input=question,
        capture_output=True,
        text=True,
        timeout=TIMEOUT_SECONDS,
    )

    if result.returncode != 0:
        raise RuntimeError(
            f"RAG subprocess failed (exit {result.returncode}):\n{result.stderr}"
        )

    data = json.loads(result.stdout.strip())

    # --------------------------------------------------------------------------
    # EXTRACT — replace these with the real keys from your CLI's JSON output
    # --------------------------------------------------------------------------
    answer: str = data["answer"]
    contexts: list[str] = data["contexts"]

    return {
        "answer": answer,
        "contexts": contexts,
        "metadata": {k: v for k, v in data.items() if k not in ("answer", "contexts")},
    }
