"""
RagSentry Adapter — Python Callable
Generated by: skills/adapter-scaffolder

Replace every <PLACEHOLDER> below with the values discovered during
the code-inspection phase of the skill.

Usage:
    ragsentry run -e evalset.jsonl -a ragsentry_adapter:query
"""
from __future__ import annotations

from typing import Any

# --------------------------------------------------------------------------
# IMPORT your RAG application's retrieval function here.
#
# Examples:
#   from myapp.rag import retrieve_and_answer
#   from myapp.pipeline import ask
#   from myapp.api.core import rag_query
# --------------------------------------------------------------------------
# from <MODULE_PATH> import <FUNCTION_NAME>


# --------------------------------------------------------------------------
# CONFIGURATION (optional)
# If your RAG function needs initialization (DB connections, model loading,
# config objects), do it here at module scope so it runs once on import,
# not on every query() call.
# --------------------------------------------------------------------------
# from myapp.config import Settings
# settings = Settings()
# rag_engine = MyRagEngine(settings)


def query(question: str) -> dict[str, Any]:
    """
    RagSentry adapter: wraps your RAG function in the standard contract.

    Must return a dict with at minimum:
        { "answer": str, "contexts": list[str] }
    """
    # ------------------------------------------------------------------
    # CALL your RAG function
    # Replace this line with your actual function call.
    # ------------------------------------------------------------------
    raw = your_rag_function(question)  # TODO: replace with real call

    # ------------------------------------------------------------------
    # EXTRACT the answer
    # Change the key or attribute to match your RAG function's output.
    #
    # Common patterns:
    #   raw["answer"]              — dict with "answer" key
    #   raw["response"]            — dict with different key name
    #   raw.answer                 — dataclass or named tuple
    #   raw.model_dump()["answer"] — Pydantic model
    # ------------------------------------------------------------------
    answer: str = raw["answer"]

    # ------------------------------------------------------------------
    # EXTRACT the contexts (retrieved passages)
    # Must be a list[str]. If your RAG returns objects, extract the text.
    #
    # Common patterns:
    #   raw["contexts"]                                — already list[str]
    #   raw["sources"]                                 — different key name
    #   [doc.page_content for doc in raw["documents"]] — LangChain Documents
    #   [chunk["text"] for chunk in raw["chunks"]]     — list of dicts
    #   [node.get_content() for node in raw["nodes"]]  — LlamaIndex nodes
    #   raw.source_nodes                               — attribute access
    # ------------------------------------------------------------------
    contexts: list[str] = raw["contexts"]

    return {
        "answer": answer,
        "contexts": contexts,
        # Optional: forward any extra metadata for traceability
        "metadata": {k: v for k, v in raw.items() if k not in ("answer", "contexts")},
    }


# --------------------------------------------------------------------------
# ASYNC VARIANT (uncomment if your RAG function is async)
#
# import asyncio
#
# async def _async_rag_call(question: str):
#     return await your_async_rag_function(question)
#
# def query(question: str) -> dict[str, Any]:
#     raw = asyncio.run(_async_rag_call(question))
#     answer = raw["answer"]
#     contexts = raw["contexts"]
#     return {"answer": answer, "contexts": contexts}
# --------------------------------------------------------------------------


# --------------------------------------------------------------------------
# SELF-TEST — run this file directly to verify the adapter works:
#   python ragsentry_adapter.py
# --------------------------------------------------------------------------
if __name__ == "__main__":
    import json

    test_question = "What is your test question here?"
    try:
        result = query(test_question)
        assert isinstance(result["answer"], str), "answer must be a string"
        assert isinstance(result["contexts"], list), "contexts must be a list"
        assert all(isinstance(c, str) for c in result["contexts"]), "each context must be a string"
        print("✓ Adapter contract verified!")
        print(json.dumps(result, indent=2, default=str))
    except Exception as e:
        print(f"✗ Adapter failed: {e}")
        raise

